### ISSUE TITLE
FT014 - feat:  wyświetlanie widoku wszystkich sekcji

### ISSUE THREAD

**Issue by jBachanek-02** [akademia-envelo-3/meetek-front#13]
**Dodatkowe informacje**

Sekcje, których ownerem jest zalogowany uzytkownik, mają miec dodatkowe buttony modifikuj /dezaktywuj (na tym etapie bez logiki).

Na razie bez działającej wyszukiwarki. 

1. Wyświetlane dane, powinny pochodzić z ngrx store (task blokujący #22).
2. Po kliknięciu w komponent z sekcją przechodzimy na podstronę sekcji.
3. Po kliknięciu w przycisk z plusem wyświetla się formularz do stworzenia sekcji. 

**Makiety**
[UC28-Display sections](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=0%3A1&t=wIKCAUvRYvYDqQG3-0)      

[figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=331%3A25376&t=ht9GjdriLijgnVFp-0)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=JYt3CImqlQ4GD88X-0)

**Taski blokujące**

 #16 #22 #5 

**Task powiązany**
#10 

**Kryteria akceptacji**
1. Wygląd jest zgodny z makietami, responsywny.
2. Jeśli jestem ownerem, wyświetlają mi się 2 dodatkowe przyciski : modyfikuj / dezaktywuj. 
3. Klikajac w kafel sekcji przechodzę podstronę sekcji. #94  
4. Klikając w przycisk plusa przechodzę na podstronę edycji sekcji. #41

**Comment by jBachanek-02** [comment]
[Widok](https://deploy-preview-82--meetek-envelo.netlify.app/sections)

**Comment by PawelJurga** [comment]
- [ ] Wygląd jest zgodny z makietami, responsywny.
 - **dla mobile i web rozjeżdżają się widoki (screeny)**

- [x] Jeśli jestem ownerem, wyświetlają mi się 2 dodatkowe przyciski : modyfikuj / dezaktywuj.

- [x] Klikając w kafel sekcji przechodzę podstronę sekcji.



- [x] Klikając w przycisk plusa przechodzę na podstronę edycji sekcji.




![Image](https://user-images.githubusercontent.com/121928858/219627272-ef05db1a-5afe-4f4c-902d-c2959c843a16.png)


![Image](https://user-images.githubusercontent.com/121928858/219627568-7c9c70ad-3e33-4861-8fba-2d9ce5641a3c.png)

**Comment by PawelJurga** [comment]
**RETEST**
po zmianach dla niektórych rozmiarów wyświetlaczy mobilnych plusik nie pojawia się w widoku 


![Image](https://user-images.githubusercontent.com/121928858/219654920-d9cc1938-9566-4ab1-9381-579c4f1d4a22.png)

**Comment by PawelJurga** [comment]
**RETEST**
"Znikający plusik" - **poprawiono**
**Rekomenduję zakończenie taska :)**
